http:
  port: ${HTTP_PORT:-8080}
  host: localhost
admin:
  port: ${ADMIN_PORT:-9876}
  host: localhost
apiEndpoints:
  patients:
    host: localhost
    paths: /patients
  staff:
    host: localhost
    paths: /staff
  login:
    host: localhost
    paths: /login
serviceEndpoints:
  patients:
    url: ${PATIENTS_URL:-http://localhost:3000}
  staff:
    url: ${STAFF_URL:-http://localhost:4000}
  login:
    url: ${LOGIN_URL:-http://localhost:5000}
policies:
  - oauth2-introspect
  - jwt
  - log
  - proxy
pipelines:
  patients:
    apiEndpoints:
      - patients
    policies:
      - jwt:
        - action:
            secretOrPublicKey: ${SECRET_KEY}
            checkCredentialExistence: false
      - log:
        - action:
            message: ${req.method} ${req.originalUrl} ${res.statusCode}
      - proxy:
        - action:
            serviceEndpoint: patients
            changeOrigin: true
  login:
    apiEndpoints:
      - login
    policies:
        - log:
           - action:
               message: ${req.method} ${req.originalUrl} ${res.statusCode}
 
