http:
  port: ${PORT:-8080}
  host: localhost
admin:
  port: ${ADMIN_PORT:-9876}
  host: localhost
apiEndpoints:
  account:
    host: '*'
    paths: ['/account','/account/*']
  users:
    host: '*'
    paths: ['/users','/users/*']
  patients:
    host: '*'
    paths: ['/patients','/patients/*']
  devices:
    host: '*'
    paths: ['/devices','/devices/*']
serviceEndpoints:
  account:
    url: ${ACCOUNT_URL:-http://localhost:2000}
  users:
    url: ${USERS_URL:-http://localhost:3000}
  patients:
    url: ${PATIENTS_URL:-http://localhost:4000}
  devices:
    url: ${DEVICES_URL:-http://localhost:5000}

policies:
  - jwt
  - log
  - proxy
pipelines:
  default:
    apiEndpoints:
      - account
      - users
      - patients
      - devices
    policies:
      - log:
        - action:
            message: ${req.method} ${req.originalUrl} ${res.statusCode}
  account:
    apiEndpoints:
      - account
    policies:
      - proxy:
        - action:
            serviceEndpoint: account
            changeOrigin: true
  users:
    apiEndpoints:
      - users
    policies:
      - jwt:
        - action:
            secretOrPublicKeyFile: ./keys/public-key.pem
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: users
            changeOrigin: true
  patients:
    apiEndpoints:
      - patients
    policies:
      - jwt:
        - action:
            secretOrPublicKeyFile: ./keys/public-key.pem
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: patients
            changeOrigin: true
  devices:
    apiEndpoints:
      - devices
    policies:
      - jwt:
        - action:
            secretOrPublicKeyFile: ./keys/public-key.pem
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: devices
            changeOrigin: true
