http:
  port: ${HTTP_PORT:-8080}
  host: localhost
admin:
  port: ${ADMIN_PORT:-9876}
  host: localhost
apiEndpoints:
  account:
    host: localhost
    methods: 'POST'
    paths: /account/*
  patients:
    host: localhost
    paths: ['/patients', '/patients/*']
serviceEndpoints:
  account:
    url: ${ACCOUNT_URL:-http://localhost:5000}
  patients:
    url: ${PATIENTS_URL:-http://localhost:3000}
policies:
  - jwt
  - log
  - proxy
pipelines:
  default:
    apiEndpoints:
      - patients
      - account
    policies:
      - log:
        - action:
            message: ${req.method} ${req.originalUrl} ${res.statusCode}
  patients:
    apiEndpoints:
      - patients
    policies:
      - jwt:
        - action:
            secretOrPublicKeyFile: ./keys/public-key.pem
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: patients
            changeOrigin: true
  account:
    apiEndpoints:
      - account
    policies:
        - proxy:
           - action:
                serviceEndpoint: account
                changeOrigin: true
