http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  patients:
    host: localhost
    paths: /patients
serviceEndpoints:
  patients:
    url: ${PATIENTS_URL:-http://localhost:3000}
policies:
  - log
  - proxy
pipelines:
  default:
    apiEndpoints:
      - patients
    policies:
      - log:
        - action:
            message: ${req.method} ${req.originalUrl} ${res.statusCode}
      - proxy:
        - action:
            serviceEndpoint: patients
            changeOrigin: true